### ISSUE TITLE
Skipping gptcommit because the githook isn't set up for this commit mode

### ISSUE THREAD

**Issue by saltbo** [zurawiki/gptcommit#103]
<img width="580" alt="image" src="https://user-images.githubusercontent.com/17308208/226154365-8a455c17-58e1-4fd8-8013-0b4fee9a18be.png">

Why?

**Comment by zurawiki** [comment]
You raise a good point that `gptcommit` isn't producing a helpful error message here. I'm going add more context.

This issue sounds similar to #13 . Can you try the debug steps here and see if this is caused by your git template?

**Comment by saltbo** [comment]
Yeah, I have a git commit template. remove it can work fine.

**Comment by vivian940425** [comment]
> Yeah, I have a git commit template. remove it can work fine.

Hi saltbo I was not able to get the template removed. any chance you can share the command to remove the template. many thanks!

**Comment by saltbo** [comment]
https://github.com/saltbo/dotfiles/blob/master/.gitconfig#L11 

I remove this line
