### ISSUE TITLE
API key doesn't update

### ISSUE THREAD

**Issue by albert-ying** [zurawiki/gptcommit#110]
I'm keep getting the error

```
Error: invalid_request_error: Incorrect API key provided: sk-eKEmW***************************************pG63. You can find your API key at https://platform.openai.com/account/api-keys.
```

This is the first API key I set, which is invalid. However, I've updated the valid API key, in `config.toml`, but this error persist and keep showing the old API-key.

I tried restart and reinstall, but doesn't work.

**Comment by zurawiki** [comment]
Try resetting your config with 
```
unset OPENAI_API_KEY
unset GPTCOMMIT__OPENAI__API_KEY
gptcommit config delete openai.api_key
gptcommit config delete --local openai.api_key
```

Then set your config

**Comment by albert-ying** [comment]
> Try resetting your config with
> 
> ```
> unset OPENAI_API_KEY
> unset GPTCOMMIT__OPENAI__API_KEY
> gptcommit config delete openai.api_key
> gptcommit config delete --local openai.api_key
> ```
> 
> Then set your config

This works for me

**Comment by zurawiki** [comment]
Closing this issue. Feel free to reopen if not resolved
