### ISSUE TITLE
Have you considered adding a proxy function?

### ISSUE THREAD

**Issue by AlliotTech** [zurawiki/gptcommit#113]
As you know, OpenAI is not available in some regions, so maybe some users need to set up a proxy for it.

**Comment by zurawiki** [comment]
Yup, see #105! Should land soon

**Comment by AlliotTech** [comment]
Hmmm, actually, I mean, is it possible to have a socks or http proxy function? not "Custom OpenAI API address"

**Comment by zurawiki** [comment]
Released in v0.5.1!

**Comment by wakeGISer** [comment]
> Released in v0.5.1!

How should i use the proxy ?

**Comment by zurawiki** [comment]
> > Released in v0.5.1!
> 
> 
> 
> How should i use the proxy ? 

See https://github.com/zurawiki/gptcommit/releases/tag/v0.5.1

**Comment by wakeGISer** [comment]
> > > Released in v0.5.1!
> > 
> > 
> > How should i use the proxy ?
> 
> See https://github.com/zurawiki/gptcommit/releases/tag/v0.5.1

I had already set the proxy config with the  `gptcommit config set openai.proxy "http://127.0.0.1:8899"` 

But it didn't work 

![image](https://user-images.githubusercontent.com/18297853/227841508-ea889341-6621-4ed2-a1e8-fc26c6b4ecdb.png)

And I can't see any request in my proxy tools
