### ISSUE TITLE
feat: How could I make title follows certain format

### ISSUE THREAD

**Issue by dannypsnl** [zurawiki/gptcommit#115]
As the question, if I would like to have `[feat] ......` rather than `feat: ......`, how could I do it? Does this need any code changes? Or it can be done with the current configuration?

**Comment by zurawiki** [comment]
You would need to make a code change for this. This code that adds the `: ` is here: 

https://github.com/zurawiki/gptcommit/blob/908f4c77c0280114ae2cedfb92cee10caec9fab5/src/summarize.rs#L92
