### ISSUE TITLE
Running git commit --> Could not decode JSON respose

### ISSUE THREAD

**Issue by iroy2000** [zurawiki/gptcommit#12]
This is my test case

I made some minor changes ( for testing purpose )
I run `git add .`
And then I run `git commit`

After that, I received this

🤖 Asking GPT-3 to summarize diffs...
Error: Could not decode JSON respose ( a typo )

Is there a verbose mode, so that the user will know what the error is and act accordingly ?

Thanks

**Comment by g12r** [comment]
Similar -- 

❯ git commit -a
🤖 Asking GPT-3 to summarize diffs...
Error: Could not decode JSON respose

**Comment by zurawiki** [comment]
Good point and thank you both for the feedback. This should be fixed in #15 giving us a better error message into what is going on.

I'll ship a new version 0.1.3 with this fix

**Comment by iroy2000** [comment]
Thanks @zurawiki , I updated the package, and now I see the error message, seems like it is an issue in `gptcommit`

```
{"error":{"code":null,"message":"Invalid URL (POST /v1/completions1)","param":null,"type":"invalid_request_error"}}
```

**Comment by iroy2000** [comment]
I opened a PR regarding to the issue above - https://github.com/zurawiki/gptcommit/pull/16

**Comment by zurawiki** [comment]
> Thanks @zurawiki , I updated the package, and now I see the error message, seems like you have a typo, it should be `completions` instead of `completions1`.
> 
> `{"error":{"code":null,"message":"Invalid URL (POST /v1/completions1)","param":null,"type":"invalid_request_error"}}`

Thanks for pointing that out! I was rushed last night uploading v0.1.3 and left that wrong endpoint in as a way to debug, sorry!

The fix is already landed to master and I've published v0.1.4. I'm still curious as to what the original error you were seeing was.

**Comment by iroy2000** [comment]
@zurawiki It's all good now.  The message comes back with reason of "insufficient quota".  Now user will have insight of what's going on!

**Comment by iroy2000** [comment]
Closing this ticket as resolved.
