### ISSUE TITLE
Skipping gptcommit because the githook isn't set up for this commit mode

### ISSUE THREAD

**Issue by AHuaner** [zurawiki/gptcommit#125]
I encountered the following problems in the process of using
![Issues](https://user-images.githubusercontent.com/17757654/227945682-4eab5bff-5bf5-4b63-87b6-1d63b28bb817.png)

**Comment by zurawiki** [comment]
Based on the output, it looks like you are not on the latest version. I recommend using v0.5.1 or later

See #103 for more context
