### ISSUE TITLE
bug: Skipping because githook is not run on commit

### ISSUE THREAD

**Issue by nixsiow** [zurawiki/gptcommit#13]
Hey there,

Thanks for creating this tool for the community. It looks very interesting on the demos.

I managed to install it using cargo and also installed the git hook on my existing git repo. I can see the git hook `prepare-commit-msg` file showing up in the hook folder. However, it won't run whenever I tried to run `git commit` (with or without flags) command. I had the `OPENAI_API_KEY` env variable setup and activated already on my machine. What do you think might be the problem?

Thanks again for your attention.

**Comment by zurawiki** [comment]
Thanks for the feedback! Can you try running the `git commit` command with the `RUST_LOG` envvar set to `trace`?

```
RUST_LOG=trace git commit ...
```

That might get give us a bit more context into what is going on

**Comment by nixsiow** [comment]
Thanks for yoru reply!

These are the outputs:

```
$ RUST_LOG=trace git commit -a
2023-01-20T04:26:30.577Z DEBUG [gptcommit] Args { action: PrepareCommitMsg(PrepareCommitMsgArgs { commit_msg_file: ".git/COMMIT_EDITMSG", commit_source: Template, commit_sha: Some(""), git_diff_content: None }) }
🤖 Skipping gptcommit because githook is not run on commit
hint: Waiting for your editor to close the file...
```

**Comment by zurawiki** [comment]
> Thanks for your reply!
> 
> These are the outputs:
> 
> ```
> $ RUST_LOG=trace git commit -a
> 2023-01-20T04:26:30.577Z DEBUG [gptcommit] Args { action: PrepareCommitMsg(PrepareCommitMsgArgs { commit_msg_file: ".git/COMMIT_EDITMSG", commit_source: Template, commit_sha: Some(""), git_diff_content: None }) }
> 🤖 Skipping gptcommit because githook is not run on commit
> hint: Waiting for your editor to close the file...
> ```

Looking at `commit_source: Template` it seems you might have a `commit template`
set. Can you try removing the `git config --local commit.template` and see if the issue goes away.

Because the githook detected the user is supplying their own template, we make sure not to overwrite it with GPT

**Comment by nixsiow** [comment]
> > ```
> > $ RUST_LOG=trace git commit -a
> > 2023-01-20T04:26:30.577Z DEBUG [gptcommit] Args { action: PrepareCommitMsg(PrepareCommitMsgArgs { commit_msg_file: ".git/COMMIT_EDITMSG", commit_source: Template, commit_sha: Some(""), git_diff_content: None }) }
> > 🤖 Skipping gptcommit because githook is not run on commit
> > hint: Waiting for your editor to close the file...
> > ```
> 
> Looking at `commit_source: Template` it seems you might have a [commit template](https://git-scm.com/docs/git-commit/2.10.5#Documentation/git-commit.txt---templateltfilegt) set. Can you try removing the `git config --local commit.template` and see if the issue goes away.
> 
> Because the githook detected the user is supplying their own template, we make sure not to overwrite it with GPT

Thanks! It is working perfectly now! Very cool! I'd prefer if there is a way, maybe with flag, to switch between using GPT and local/global commit template. Or perhaps, a wrap over `git commit -a` with custom flag to overwrite the local/global template. Anyway, thanks a lot for your help!

**Comment by roukmoute** [comment]
It's great that it works! 

I think you can now close the ticket, but it would be an added bonus to update the README file with a section on "frequent problems". What do you think?

**Comment by zurawiki** [comment]
Good point, I've updated the readme.

**Comment by LouisShark** [comment]
<img width="1538" alt="Screenshot 2023-02-14 at 02 37 07" src="https://user-images.githubusercontent.com/18005609/218545229-910d52e8-7bf9-46b4-afce-f25f731366b4.png">
the same error @zurawiki
