### ISSUE TITLE
gpt-3.5-turbo-16k support

### ISSUE THREAD

**Issue by CyshallChan** [zurawiki/gptcommit#174]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zurawiki** [comment]
This is now supported with new releases of tiktoken-rs v0.4.3 and gptcommit v0.5.9

You can update your config to use the larger model with

```sh
gptcommit config set openai.model gpt-3.5-turbo-16k
```
