### ISSUE TITLE
bug: You didn't provide an API key

### ISSUE THREAD

**Issue by JKamsker** [zurawiki/gptcommit#202]
**Describe the bug**
``git commit -a`` produces 
```md
🤖 Let's ask OpenAI to summarize those diffs! 🚀
Error: invalid_request_error: You didn't provide an API key. You need to provide your API key in an Authorization header using Bearer auth (i.e. Authorization: Bearer YOUR_KEY), or as the password field (with blank username) if you're accessing the API from your browser and are prompted for a username and password. You can obtain an API key from https://platform.openai.com/account/api-keys.
```

``gptcommit config list``
clearly shows ``api_key = "sk-[MY API KEY lol]"``

The api key should work according to a tests with postman.

**System Info (please complete the following information):**
 - OS: Windows
 - Version 0.5.10

**Comment by mcourteaux** [comment]
This code should probably be chained, instead of nested, as it goes with Builder patterns.

**Comment by zurawiki** [comment]
Thanks for the feedback. I am addressing this in #205
