### ISSUE TITLE
support conventional commits

### ISSUE THREAD

**Issue by 6r17** [zurawiki/gptcommit#22]
**Suggestion:** Add support for Semantic Versioning, using tags ( such as [dev] [chore] [fix] [perf]) appropriately 
**Why:** Semantic is a widely known standard for commit messages which are compiled to make a description of new releases. https://github.com/semantic-release/semantic-release
**How:** Add [dev] [chore] etc... in the commit message ; might be wrong but we are editing the message already anyway
**What:** Maybe a configuration that we could setup to automaticly prefix the commit message, maybe there is a way to hack this in without modifying the code too much ?

**Comment by zurawiki** [comment]
Thanks for the suggestions @6r17 , I appreciate the feedback!

I see value in implementing this feature outside of the LLM APIs. I'm curious if we can categorize a diff based on the change and apply the right label (chore, doc, fix, feat, etc.).
