### ISSUE TITLE
How to temporarily disable gptcommit for manual git commit message entry?

### ISSUE THREAD

**Issue by Mlearn** [zurawiki/gptcommit#265]
Awesome project! It has been incredibly useful for my work.

After utilizing this tool for a period of time, I would like to know how I can temporarily disable gptcommit and revert to the traditional method of manually entering commit messages.

**Comment by andreagrandi** [comment]
I was about to ask the same 😅
I would love an option to exclude automatic generation of the commit message.

**Comment by luochen1990** [comment]
Just `git commit -m 'your message'`  ?

**Comment by zurawiki** [comment]
`git commit -n` also works, disabling any git hooks 

```
$ git help commit
...
       -n, --[no-]verify
           By default, the pre-commit and commit-msg hooks are run. When any
           of --no-verify or -n is given, these are bypassed. See also
           githooks(5).
...
```
