### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by RRadziejewski** [zurawiki/gptcommit#27]
Hello I'm totally not into Rust environment. Decided to share it and luckily get some valid answer instead of copy pasting dunno what.

```
  rra@whatisthat:~/Documents/siemens/SDI/build-image$ cargo install --locked gptcommit
      Updating crates.io index
    Installing gptcommit v0.1.4
  error: failed to compile `gptcommit v0.1.4`, intermediate artifacts can be found at `/tmp/cargo-installBD3IP0`
  
  Caused by:
    package `clap_lex v0.3.1` cannot be built because it requires rustc 1.64.0 or newer, while the currently active rustc version is 1.61.0
  rra@workmachine:~/Documents/siemens/SDI/build-image$ 

```

**Comment by DJDuque** [comment]
Run `rustup update` and then try to install again. As the error message points out, you have and older version of the rust compiler installed than the minimum required to build this project.

**Comment by zurawiki** [comment]
@DJDuque is correct here. The supported rust_version is `rust-version = "1.66"` as defined in `Cargo.toml`
