### ISSUE TITLE
Support for gpt-4o

### ISSUE THREAD

**Issue by bbigras** [zurawiki/gptcommit#274]
It might be a dumb question, but could gptcommit be used with the gpt-4o model?

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by zurawiki** [comment]
Yes, models are configurable with the config below:

    gptcommit config set openai.model gpt-4o-2024-05-13 # or any other OpenAI model
