### ISSUE TITLE
bug: windows install gptcommit  v0.5.16 is fail by cargo

### ISSUE THREAD

**Issue by Zander-1024** [zurawiki/gptcommit#275]
**Describe the bug**

**To Reproduce**
use cargo install  gptcommit  v0.5.16

**Expected behavior**

**Screenshots**
![image](https://github.com/zurawiki/gptcommit/assets/34827878/e79ee3b3-2836-4997-bafe-ead9139d197c)
**Run your command with the `RUST_LOG=trace` environment variable** for the best support 

**System Info (please complete the following information):**
 - OS:  Windows
 - Version v0.5.16

**Additional context**
error[E0635]: unknown feature `stdsimd`                                                                                                                                                                                          
  --> C:\Users\zhuang\.cargo\registry\src\index.crates.io-6f17d22bba15001f\ahash-0.7.7\src/lib.rs:33:42
   |
33 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^

**Comment by zurawiki** [comment]
Hi @Zander-1024 , thanks for the details bug report. This should be fixed with the latest version of Rust and gptcommit 0.5.17
