### ISSUE TITLE
Allow custom max summary length

### ISSUE THREAD

**Issue by rusmux** [zurawiki/gptcommit#29]
Right now, the max summary length is hard-coded and is 3000. I think it would be nice to allow users to change that threshold if needed.

**Comment by zurawiki** [comment]
Thanks for the feedback @rusmux! Right now the token length is a limit from the OpenAI servers.  I did recently update the logic to allow for more tokens with the default model.

As a followup, I'm looking at more AI technique to allow breaking up longer changes as well!
