### ISSUE TITLE
bug: brew install failed

### ISSUE THREAD

**Issue by takenokos** [zurawiki/gptcommit#290]
**Describe the bug**
brew install failed

**To Reproduce**
1. brew install zurawiki/brews/gptcommit

**Expected behavior**
brew insall successful

**Screenshots**
**Run your command with the `RUST_LOG=trace` environment variable** for the best support 
![image](https://github.com/user-attachments/assets/6eb8c2c8-d638-438c-b358-cb9293fdd32b)

**System Info (please complete the following information):**
 - OS: macOS Sequoia 15.0
 - Version: 

**Additional context**
`cargo install --locked gptcommit` install v0.5.16 has same issue

**Comment by sandydoo** [comment]
PR: https://github.com/zurawiki/gptcommit/pull/285
