### ISSUE TITLE
Allow to force overwrite commit message on git commit --amend 

### ISSUE THREAD

**Issue by rusmux** [zurawiki/gptcommit#30]
After resolving issue #2 commit message is not overwritten by `git commit --amend`, however, there are still use cases when one would want to overwrite the commit message. 

How about to add something like `--force` option to allow users to force overwrite commit messages?

**Comment by zurawiki** [comment]
We could implement this option as a setting. 

I'm open to suggestions for names.

I'm thinking something along the lines of:
```
gptcommit config set source.allow-amend true
```
Any better ideas?

**Comment by zurawiki** [comment]
Done in v0.1.12

Enable it with 
```
gptcommit config set allow-amend true
```
