### ISSUE TITLE
Allow config file per-repo

### ISSUE THREAD

**Issue by friuns2** [zurawiki/gptcommit#31]
is there way to customize your prompt template?

**Comment by zurawiki** [comment]
I'm thinking about building this functionality into the tool.

How do you think this should work from a user perspective?

**Comment by friuns2** [comment]
I modified it to write update announcements for my game, less detailed and more user friendly. I think ability to put context of the project is important.

**Comment by zurawiki** [comment]
Got it. I added the ability to specify custom prompts via config (check out `gptcommit config list`)

We need to follow up and allow for git repo-local config

**Comment by zurawiki** [comment]
Fixed in v0.1.17. See README or executable's help for usage of the `gptcommit config --local` flag
