### ISSUE TITLE
Allow to keep git diff at end of message

### ISSUE THREAD

**Issue by vitalwarley** [zurawiki/gptcommit#34]
I think it would be good to have it as an option for verification purposes -- to check if the summary really captures the gist of the diff.

**Comment by vitalwarley** [comment]
It can be checked with `git commit --amend`. However, this is a second step that could be avoided in some cases.

**Comment by zurawiki** [comment]
Done in #38

Instead of overwriting the commit message, we prepend to it

**Comment by zurawiki** [comment]
See release 0.1.12
