### ISSUE TITLE
[Thanks] vscode-gptcommit

### ISSUE THREAD

**Issue by pwwang** [zurawiki/gptcommit#50]
Just want to say thank you for developing this.

I've wrapped this into a VS Code extension.

https://github.com/pwwang/vscode-gptcommit
https://marketplace.visualstudio.com/items?itemName=pwwang.gptcommit

See if you are interested in contributing as well.

**Comment by zurawiki** [comment]
Thank @pwwang, this is great to see! I don't use the VScode UI much for interacting with git but I'll mention this project in the README here. Let me know if this tool leads to any feature requests fir this project.
