### ISSUE TITLE
[Feature Request] Per-project configuration

### ISSUE THREAD

**Issue by pwwang** [zurawiki/gptcommit#53]
Now, `gptcommit` uses a global configuration, including API keys, prompts, etc. Is it possible to have per-project configurations? 

For example, with a per-project `prompt`, I can have only `title`s for some projects, or I can add some specific characters in the messages, for example, some emojis.

One solution I can think of is to have a configuration file `./.gptcommit/config.toml`, which overwrites the global one. 

It is also helpful for us to use different API keys and track their usage for different projects.

**Comment by zurawiki** [comment]
Solving this in #54

**Comment by zurawiki** [comment]
Fixed in v0.1.17. See README or executable's help for usage of the `gptcommit config --local` flag
