### ISSUE TITLE
support chatGPT model

### ISSUE THREAD

**Issue by lsdventures** [zurawiki/gptcommit#65]
When trying to set `gptcommit config set openai.model gpt-3.5-turbo`

after that, when using gptcommit, It shows the error 

```OpenAI error: This is a chat model and not supported in the v1/completions endpoint. Did you mean to use v1/chat/completions?```

reference: https://openai.com/blog/introducing-chatgpt-and-whisper-apis

**Comment by zurawiki** [comment]
Stay posted for a minor version release here!
