### ISSUE TITLE
How to install to GitHub CodeSpaces?

### ISSUE THREAD

**Issue by BoQsc** [zurawiki/gptcommit#76]
I'm having a hard time finding a way to install it into github codespace.

**Comment by zurawiki** [comment]
On linux, the supported way to install `gptcommit` is via `cargo install`.

In your devcontainer, you will have to make sure the rust toolchain is installed (including cargo). This should be pre-installed by a number of Microsoft containers. From there, you'll add a script to run `cargo install --locked gptcommit`.

Let me know if that answers your question

**Comment by BoQsc** [comment]
What worked for me is typing typing these commands in the terminal:
```bash
curl https://sh.rustup.rs -sSf | sh
bash
cargo install --locked gptcommit

# insert your openai api key https://platform.openai.com/account/api-keys
gptcommit config set openai.api_key sk-

```

setting the gptcommit location in the gptcommit extension settings
```bash
gptcommit
whereis gptcommit
	gptcommit: /home/codespace/.cargo/bin/gptcommit

```

![image](https://user-images.githubusercontent.com/21064622/223098177-26b25517-8bdd-4563-b0d5-3ff7816ea278.png)

**Comment by zurawiki** [comment]
Great! Are we good to close out this issue then?

**Comment by BoQsc** [comment]
Well it's still an issue until it's well documented and integrated into documentation.
Else these issues will be repeated in the future. 
But that's only my own opinion.
You can close, if you feel like.

**Comment by zurawiki** [comment]
Updated the README documentation. Closing
