### ISSUE TITLE
Disable per-file summary

### ISSUE THREAD

**Issue by pwwang** [zurawiki/gptcommit#81]
Is it possible for us to disable per-file summary?

Sometimes there might be just one file or a few files changed. The per-file summary might be redundant with the main title and summary.

It's also useful to save costs.

**Comment by zurawiki** [comment]
Hey @pwwang,

The per-file summary can be disabled with 
```
gptcommit config set output.show_per_file_summary false
```
 
 You can reenable it with
```
gptcommit config set output.show_per_file_summary false
```

In the future, I'd like to consider how we can re-tool the prompt to use fewer queries. If you have suggestions for that, I'd to love hear more!

**Comment by pwwang** [comment]
Great, I'm glad that the per-file summary can be disabled. Is it available since v0.3.0? Because I don't see this configuration key by `gptcommit config keys`.

I've been working on improving the user experience for [vscode-gptcommit](https://github.com/pwwang/vscode-gptcommit) users, and have created configurations that allow for different combinations of commit messages. These include:

- title (only the title)
- title + summary (title and bullet-point summaries)
- title + breakdown (title and pre-file summaries)
- title + summary + breakdown (title, bullet-point summaries and per-file summaries)

At present, I'm using filtering to manage the text returned by `gptcommit` to produce these message combinations, however, having built-in settings with `gptcommit` would be ideal. 

Thanks for considering this, and please let me know if you need more information or have any questions.

**Comment by zurawiki** [comment]
I just release 0.3.1 with some new settings.

I'm happy to accept a PR to enable / disable the summary. It's not something I have bandwidth to prioritize right now

**Comment by zurawiki** [comment]
Hey @pwwang , since adding the latest settings for `output.show_per_file_summary` can we close this issue, or are the bullet points still necessary?

**Comment by pwwang** [comment]
No, this is perfectly solved. Thanks!
